### ISSUE TITLE
Does not work with SharedWorker

### ISSUE THREAD

**Issue by bryaan** [kwolfy/webworker-promise#21]
This lib does not work for Shared WebWorkers.

```
const worker = new WebworkerPromise(new SharedWorker('worker.ts'));

dex.js:67 Uncaught (in promise) TypeError: this._worker.postMessage is not a function
    at index.js:67:20
    at new Promise (<anonymous>)
    at Worker.postMessage (index.js:64:12)
 
```

**Comment by kwolfy** [comment]
SharedWorker has a significantly different interface than regular Workers. I think in theory it is possible to implement support for them, but it requires significant improvements

**Comment by kwolfy** [comment]
I have a plan to implement a more universal library with support for node thread_workers, ServiceWorkers, SharedWorkers. But I can't predict when it will be ready yet
